export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';

export const ADD_CART = 'ADD_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const REMOVE_ALL_CART = 'REMOVE_ALL_CART';
export const TOTAL_QTY_CART = 'TOTAL_QTY_CART'

export const SET_LIST_USER_ADDRESSES = 'SET_LIST_USER_ADDRESSES';
export const UNSET_LIST_USER_ADDRESSES = 'UNSET_LIST_USER_ADDRESSES';

export const SET_LIST_ORDER = 'SET_LIST_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const SELECT_ORDER = 'SELECT_ORDER';
export const UNSET_LIST_ORDER = 'UNSET_LIST_ORDER';