# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Craftcology' do
    # this is very important to have!
    rn_path = '../node_modules/react-native'
    pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
    pod 'React', path: rn_path, subspecs: [
        'Core',
        'RCTActionSheet',
        'RCTAnimation',
        'RCTGeolocation',
        'RCTImage',
        'RCTLinkingIOS',
        'RCTNetwork',
        'RCTSettings',
        'RCTText',
        'RCTVibration',
        'RCTWebSocket'
    ]

    pod 'FacebookSDK'
    pod 'Firebase/Core', '~> 5.15.0'
    pod 'Firebase/Auth', '~> 5.15.0'

    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

    pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end

